sudo: false
dist: trusty
language: c
compiler:
  - gcc
cache:
  directories:
    - $HOME/.cache
notifications:
  email: false
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - re2c
matrix:
    include:
    - name: "3.16 master with Sequencer"
      env: BASE=3.16  STATIC=shared SSCAN=master SNCSEQ=2.2.5
        
    - name: "3.16 master without Sequencer"
      env: BASE=3.16  STATIC=shared SSCAN=master 
    
    - name: "3.15 master with Sequencer"
      env: BASE=3.15  STATIC=shared SSCAN=master  SNCSEQ=2.2.5
        
    - name: "3.15 master without Sequencer"
      env: BASE=3.15  STATIC=shared SSCAN=master 
        
    - name: "3.14 master with Sequencer"
      env: BASE=3.14  STATIC=shared SSCAN=master  SNCSEQ=2.2.5
    
    - name: "3.14 master without Sequencer"
      env: BASE=3.14  STATIC=shared SSCAN=master 
        
    - name: "Windows Shared with Sequencer"
      env: BASE=3.16  STATIC=shared CMPLR=clang WINE=32 SSCAN=master  SNCSEQ=2.2.5
        
    - name: "Windows Shared without Sequencer"
      env: BASE=3.16  STATIC=shared CMPLR=clang WINE=32 SSCAN=master 
        
    - name: "Windows Static with Sequencer"
      env: BASE=3.16  STATIC=static CMPLR=clang WINE=32 SSCAN=master  SNCSEQ=2.2.5
        
    - name: "Windows Static without Sequencer"
      env: BASE=3.16  STATIC=static CMPLR=clang WINE=32 SSCAN=master 
    

        
before_install: chmod +x ./.ci/assemble_synApps.sh

install: ./.ci/assemble_synApps.sh
     
script: 
  # Build the module
  - make
  - $TRAVIS_BUILD_DIR/tests/O.linux-x86_64/acalcTest
  - $TRAVIS_BUILD_DIR/tests/O.linux-x86_64/scalcTest
 
